import { Module } from "@/redux/slices/courseContentSlice";

export const sampleCourseModules: Module[] = [
    {
        id: "MODULE-1",
        courseId: "SAMPLE", // Replace with actual course ID
        title: "Module 1: Introduction to JavaScript",
        description: "Learn the basics of JavaScript programming",
        order: 1,
        lectures: [
            {
                id: "LECTURE-1-1",
                title: "Welcome to JavaScript",
                description: "Overview of JavaScript and what you'll learn in this course",
                videoUrl: "https://www.youtube.com/watch?v=W6NZfCO5SIk",
                duration: 15,
                order: 1,
                isPreview: true, // Free preview
            },
            {
                id: "LECTURE-1-2",
                title: "Setting Up Your Environment",
                description: "Install Node.js, VS Code, and set up your development environment",
                videoUrl: "https://www.youtube.com/watch?v=TlB_eWDSMt4",
                duration: 20,
                order: 2,
                isPreview: true, // Free preview
            },
            {
                id: "LECTURE-1-3",
                title: "Variables and Data Types",
                description: "Understanding var, let, const, and JavaScript data types",
                videoUrl: "https://www.youtube.com/watch?v=edlFjlzxkSI",
                duration: 25,
                order: 3,
                isPreview: false, // Requires enrollment
            },
            {
                id: "LECTURE-1-4",
                title: "Operators and Expressions",
                description: "Mathematical, logical, and comparison operators",
                videoUrl: "https://www.youtube.com/watch?v=FZzyij41mHg",
                duration: 18,
                order: 4,
                isPreview: false,
            },
        ],
    },
    {
        id: "MODULE-2",
        courseId: "SAMPLE",
        title: "Module 2: Control Flow and Functions",
        description: "Master conditional statements and function declarations",
        order: 2,
        lectures: [
            {
                id: "LECTURE-2-1",
                title: "If-Else Statements",
                description: "Making decisions in your code with conditionals",
                videoUrl: "https://www.youtube.com/watch?v=IsG4Xd6LlsM",
                duration: 22,
                order: 1,
                isPreview: false,
            },
            {
                id: "LECTURE-2-2",
                title: "Switch Statements",
                description: "Alternative way to handle multiple conditions",
                videoUrl: "https://www.youtube.com/watch?v=7rc8aDtVFvE",
                duration: 15,
                order: 2,
                isPreview: false,
            },
            {
                id: "LECTURE-2-3",
                title: "Loops: For and While",
                description: "Repeating code execution with loops",
                videoUrl: "https://www.youtube.com/watch?v=s9wW2PpJsmQ",
                duration: 30,
                order: 3,
                isPreview: false,
            },
            {
                id: "LECTURE-2-4",
                title: "Functions Basics",
                description: "Creating reusable code with functions",
                videoUrl: "https://www.youtube.com/watch?v=N8ap4k_1QEQ",
                duration: 28,
                order: 4,
                isPreview: false,
            },
            {
                id: "LECTURE-2-5",
                title: "Arrow Functions and Callbacks",
                description: "Modern JavaScript function syntax",
                videoUrl: "https://www.youtube.com/watch?v=h33Srr5J9nY",
                duration: 25,
                order: 5,
                isPreview: false,
            },
        ],
    },
    {
        id: "MODULE-3",
        courseId: "SAMPLE",
        title: "Module 3: Arrays and Objects",
        description: "Working with complex data structures",
        order: 3,
        lectures: [
            {
                id: "LECTURE-3-1",
                title: "Introduction to Arrays",
                description: "Creating and manipulating arrays",
                videoUrl: "https://www.youtube.com/watch?v=oigfaZ5ApsM",
                duration: 20,
                order: 1,
                isPreview: false,
            },
            {
                id: "LECTURE-3-2",
                title: "Array Methods",
                description: "Map, filter, reduce, and more",
                videoUrl: "https://www.youtube.com/watch?v=R8rmfD9Y5-c",
                duration: 35,
                order: 2,
                isPreview: false,
            },
            {
                id: "LECTURE-3-3",
                title: "JavaScript Objects",
                description: "Creating and working with objects",
                videoUrl: "https://www.youtube.com/watch?v=-e5h4IGKZRY",
                duration: 25,
                order: 3,
                isPreview: false,
            },
            {
                id: "LECTURE-3-4",
                title: "Object Methods and This",
                description: "Understanding object methods and the 'this' keyword",
                videoUrl: "https://www.youtube.com/watch?v=gvicrj31JOM",
                duration: 22,
                order: 4,
                isPreview: false,
            },
        ],
    },
    {
        id: "MODULE-4",
        courseId: "SAMPLE",
        title: "Module 4: DOM Manipulation",
        description: "Interact with web pages using JavaScript",
        order: 4,
        lectures: [
            {
                id: "LECTURE-4-1",
                title: "What is the DOM?",
                description: "Understanding the Document Object Model",
                videoUrl: "https://www.youtube.com/watch?v=0ik6X4DJKCc",
                duration: 18,
                order: 1,
                isPreview: false,
            },
            {
                id: "LECTURE-4-2",
                title: "Selecting Elements",
                description: "getElementById, querySelector, and more",
                videoUrl: "https://www.youtube.com/watch?v=y17RuWkWdn8",
                duration: 25,
                order: 2,
                isPreview: false,
            },
            {
                id: "LECTURE-4-3",
                title: "Modifying Elements",
                description: "Changing content, styles, and attributes",
                videoUrl: "https://www.youtube.com/watch?v=XY96d0vEdFk",
                duration: 30,
                order: 3,
                isPreview: false,
            },
            {
                id: "LECTURE-4-4",
                title: "Event Listeners",
                description: "Responding to user interactions",
                videoUrl: "https://www.youtube.com/watch?v=XF1_MlZ5l6M",
                duration: 28,
                order: 4,
                isPreview: false,
            },
            {
                id: "LECTURE-4-5",
                title: "Building a Mini Project",
                description: "Create an interactive to-do list application",
                videoUrl: "https://www.youtube.com/watch?v=Ttf3CEsEwMQ",
                duration: 45,
                order: 5,
                isPreview: false,
            },
        ],
    },
];
