services:

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: learnandgrow
      MONGO_INITDB_ROOT_PASSWORD: Learn&Grow@2026_DB!
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: learnandgrow
      ME_CONFIG_MONGODB_ADMINPASSWORD: Learn&Grow@2026_DB!
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo_data:
